def notifyObj
node {
   env.WORKSPACE=pwd()
   try{
     stage("Checkout"){
         dir("ossim-ci"){
            git branch: "${OSSIM_GIT_BRANCH}", url: 'https://github.com/ossimlabs/ossim-ci.git'
         }
         dir("ossim-rpm"){
            git branch: "${OSSIM_GIT_BRANCH}", url: 'https://github.com/ossimlabs/ossim-rpm.git'
         }
       notifyObj = load "${env.WORKSPACE}/ossim-ci/jenkins/pipeline/notify.groovy"
     }
     echo "${env.WORKSPACE}"
     stage("Download Artifacts"){
       step ([$class: 'CopyArtifact',
          projectName: "ossim-${OSSIM_GIT_BRANCH}",
          filter: "artifacts/ossim-install.tgz",
          flatten: true,
          target: "${env.WORKSPACE}/ossim-install"])
       step ([$class: 'CopyArtifact',
          projectName: "oldmar-${OSSIM_GIT_BRANCH}",
          filter: "artifacts/ossim-install.tgz",
          flatten: true,
          target: "${env.WORKSPACE}/oldmar-install"])
       step ([$class: 'CopyArtifact',
          projectName: "ossim-isa-plugin-${OSSIM_GIT_BRANCH}",
          filter: "ossim-isa-plugin-install.tgz",
          flatten: true,
          target: "${env.WORKSPACE}/ossim-isa-plugin-install"])
       step ([$class: 'CopyArtifact',
          projectName: "ossim-csm-plugin-${OSSIM_GIT_BRANCH}",
          filter: "ossim-csm-plugin-install.tgz",
          flatten: true,
          target: "${env.WORKSPACE}/ossim-csm-plugin-install"])
       step ([$class: 'CopyArtifact',
          projectName: 'ossim-rpm-dependencies',
          filter: "dependency-rpms.tgz",
          flatten: true,
          target: "${env.WORKSPACE}"])
     }
     stage("Build"){
      dir("${env.WORKSPACE}"){
        sh "tar xvfz dependency-rpms.tgz"
        sh "ossim-rpm/scripts/rpmbuild-binary.sh"
      }
     }
     
     stage("Archive"){
       dir("${env.WORKSPACE}/artifacts"){
           sh "mv ${env.WORKSPACE}/rpms.tgz ."
       }
       archiveArtifacts 'artifacts/*'
    }
    stage("Clean Workspace"){
      step([$class: 'WsCleanup'])
    }
  }
  catch(e)
  {
    currentBuild.result = "FAILED"
  }
}
